### PR TITLE
Look for a GitHub repository, and qualify the ML/subscribe checks accordingly

### LINKED ISSUE #408: "Mailing List" check doesn't account for groups using GitHub Issues
The CSSWG, CSS Houdini TF, and FXTF are all using GitHub Issues as their primary communication mechanism.  We're no longer recommending using www-style for general comment; it's reserved for publication announcements, pings for review, and the occasional general-interest question.

As such, the current CSSWG boilerplate omits explicit mention of sending email to www-style, and instead links to the Issues page for our repo. It does include a link to the mail archive, however.  (See the second paragraph of <https://drafts.csswg.org/css-values/#status> for an example.)

I'm currently failing Specberus due to this.  It would be nice to not have to lie about our preferred communication medium just to pass.

### PR DESCRIPTION
**Pull request by tabatkins**
Fixes #408.

### CODE REVIEW

**Comment by tabatkins** [comment]
@deniak @plehegar This looks like a spurious CI failure.

File: lib/rules/sotd/mailing-list.js [hunk 1]
```diff
@@ -39,9 +40,15 @@ exports.check = function (sr, done) {
             foundArch = true;
             return;
         }
+        if (/^https:\/\/github.com\/[\w-]+\/[\w-]+/.test(href)) {
```
Comment (deniak) [inline lib/rules/sotd/mailing-list.js]: For that rule, it might be safer to look for the issues of the repo (`/^https:\/\/github.com\/[\w-]+\/[\w-]+/issues`). There could be other GH links in the SotD for different purposes.

**Comment by tabatkins** [comment]
@deniak Ok, went ahead and checked for the issues link specifically. I'm already including a direct link in the CSS boilerplate, so that definitely won't block my publication. ^_^
