### PR TITLE
Give out error if the h2 profile cannot be found

### LINKED ISSUE #1209: Profile dectection error
If specberus cannot guess the profile from the `<h2>`, the error is a bit confusing:
`[EXCEPTION] The document could not be parsed, it's neither a TR document nor a Member Submission.`

If specberus cannot guess the profile because of the [recent subtitle rule update](https://github.com/w3c/specberus/pull/1201), then it should report that the id should be removed.

### PR DESCRIPTION
**Pull request by jennyliang220**
Resolves #1209

### CODE REVIEW

File: lib/validator.js [hunk 1]
```diff
@@ -288,6 +288,11 @@ Specberus.prototype.getDocumentDate = function () {
     const element = this.jsDocument.querySelector(
         'body div.head h2:not(#subtitle)'
     );
+    if (!element) {
```
Comment (deniak) [inline lib/validator.js:291]: Adding the error here makes it more difficult to test with the current test suite (note that the test suite is broken with that update).
It seems more appropriate to update `lib/rules/metadata/profile.js` and `lib/rules/metadata/docDate.js` instead which are the rules used when selecting the profile 'auto'.
https://github.com/w3c/specberus/blob/main/lib/l10n-en_GB.js#L26 should also be updated to provide the same kind of details.

**Review by deniak — CHANGES_REQUESTED** [review]

**Review by deniak — APPROVED** [review]
