### PR TITLE
Report better error if the document is TR but not valid (cannot find profile)

### LINKED ISSUE #1234: Bug: [EXCEPTION] The document could not be parsed, it's neither a TR document nor a Member Submission.
The error gives no indication what could be wrong. The document is produced by bikeshed and looks just like all the other TR docs that CSSWG publish.

Found [while checking `https://www.w3.org/TR/2021/WD-web-animations-1-20210513/`](https://www.w3.org/pubrules/?url=https://www.w3.org/TR/2021/WD-web-animations-1-20210513/&profile=auto).

### PR DESCRIPTION
**Pull request by jennyliang220**
resolves #1234 with reporting error:

> Pubrules is having a hard time identifying the profile of the document @@docTitle from its &lt;h2&gt;. Please make sure the &lt;h2&gt; is in a valid format: <pre><code>&lt;h2&gt;W3C (type of the document) DD Month YYYY&lt;/h2&gt;</code></pre>

see screenshot:
Screen Shot 2021-06-07 at 4 32 36 PM

### CODE REVIEW

File: lib/rules/metadata/profile.js [hunk 1]
```diff
@@ -145,6 +145,14 @@ exports.check = async function (sr, done) {
             sr.throw(
                 `[EXCEPTION] The document "${docTitle}" seems to be an Editor's Draft, which is not supported.`
             );
+        } else if (
+            sr.jsDocument.querySelector(
+                'link[href^="https://www.w3.org/StyleSheets/TR/"]'
+            )
+        ) {
+            sr.throw(
+                `Pubrules is having a hard time identifying the profile of the document "${docTitle}" from its &lt;h2&gt;. Please make sure the &lt;h2&gt; is in a valid format: <pre><code>&lt;h2&gt;W3C (type of the document) DD Month YYYY&lt;/h2&gt;</code></pre>`
```
Comment (deniak) [inline lib/rules/metadata/profile.js:154]: Please list all the profiles doc and point to `#dateTitleH2` so people will know exactly the h2 needed.

**Review by deniak — CHANGES_REQUESTED** [review]

**Comment by jennyliang220** [comment]
5841623732350_ pic_hd

File: lib/rules/metadata/profile.js [hunk 2]
```diff
@@ -145,6 +144,14 @@ exports.check = async function (sr, done) {
...
...>Candidate Recommendation Draft</a></li><li>Document for <a href="./doc/rules/?profile=CR-AMENDED#dateTitleH2">Candidate Amended Recommendation</a></li><li>Document for <a href="./doc/rules/?profile=PR#dateTitleH2">Proposed Recommendation</a></li><li>Document for <a href="./doc/rules/?profile=PR-AMENDED#dateTitleH2">Proposed Amended Recommendation</a></li><li>Document for <a href="./doc/rules/?profile=REC#dateTitleH2">Recommendation</a></li><li>Document for <a href="./doc/rules/?profile=REC-AMENDED#dateTitleH2">Amended Recommendation</a></li><li>Document for <a href="./doc/rules/?profile=REC-RSCND#dateTitleH2">Rescinded Recommendation</a></li></ul>Notes:<ul><li>Document for <a href="./doc/rules/?profile=FPIG-NOTE#dateTitleH2">First Public Interest Group Note</a></li><li>Document for <a href="./doc/rules/?profile=IG-NOTE#dateTitleH2">Interest Group Note</a></li><li>Document for <a href="./doc/rules/?profile=FPWG-NOTE#dateTitleH2">First Public Working Group Note</a></li><li>Document for <a href="./doc/rules/?profile=WG-NOTE#dateTitleH2">Working Group Note</a></li></ul>Submissions:<ul><li>Document for <a href="./doc/rules/?profile=MEM-SUBM#dateTitleH2">Member Submission</a></li></ul>`
```
Comment (deniak) [inline lib/rules/metadata/profile.js:153]: It might be better to generate the list from the profiles like we do in the [doc page](https://github.com/w3c/specberus/blob/main/views/doc/index.handlebars) instead of hardcoding the list. It's easy to forget if we add/remove profiles.

**Review by deniak — CHANGES_REQUESTED** [review]

**Comment by jennyliang220** [comment]
5851623744702_ pic_hd

File: lib/rules/metadata/profile.js [hunk 3]
```diff
@@ -145,6 +144,23 @@ exports.check = async function (sr, done) {
...
+        } else if (
+            sr.jsDocument.querySelector(
+                'link[href^="https://www.w3.org/StyleSheets/TR/"]'
+            )
+        ) {
+            const { sortedProfiles } = require('../../views');
+            let profileList = '';
+            sortedProfiles.forEach((categary) => {
+                profileList += `${categary.name}<ul>`;
+                categary.profiles.forEach((profile) => {
```
Comment (deniak) [inline lib/rules/metadata/profile.js:156]:
```suggestion
            sortedProfiles.forEach((category) => {
                profileList += `${category.name}<ul>`;
                category.profiles.forEach((profile) => {
```

**Review by deniak — CHANGES_REQUESTED** [review]

**Review by deniak — APPROVED** [review]
