### PR TITLE
fix(rules/headers/mailing-list): drop mailing list in header rule

### LINKED ISSUE #1308: Drop mailing list requirement in header
Despite the warning from Specberus, seems that few specs (I actually can't find any!) include a mailing list in the header of the document. 

Could we just drop this requirement entirely? 

For ReSpec at least, the mailing list link is included in the SoTD.

### PR DESCRIPTION
**Pull request by marcoscaceres**
closes #1308 (See bug for details)

### CODE REVIEW

**Review by jennyliang220 — APPROVED** [review]
Approved after a few minor changes.

File: test/rules.js [hunk 1]
```diff
@@ -327,18 +327,15 @@ const tests = {
...
             },
             {
                 doc: 'sotd/ml-bad.html',
-                errors: ['headers.mailing-list.no-repo'],
-                warnings: [
-                    'headers.mailing-list.no-list',
-                    'headers.mailing-list.no-arch',
-                ],
+                errors: ['headers.github-repo.no-repo'],
+                warnings: [],
```
Comment (deniak) [inline test/rules.js:338]:
```suggestion
```

**Review by deniak — CHANGES_REQUESTED** [review]
@jennyliang220 since you are renaming the rule, can you also rename and rework the test files `sotd/ml-*` to test the following cases:
* https://github.com/w3/foo/issues/
* https://github.com/w3/foo/labels/
* missing repository

**Review by deniak — APPROVED** [review]
