### PR TITLE
check specific requirements for IG notes

### LINKED ISSUE #616: Bug in rules: Expected patent policy is wrong for IG Notes
Specberus doesn't look for the right patent policy text. It's causing 2 rules to fail (deliverers and pp)

Found [while checking `https://www.w3.org/TR/2017/NOTE-pwp-20170502/`](https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2017%2FNOTE-pwp-20170502%2F&profile=IG-NOTE&validation=simple-validation&noRecTrack=true&informativeOnly=false&echidnaReady=false&patentPolicy=pp2004).

cc @iherman

### PR DESCRIPTION
**Pull request by deniak**
fix #616

### CODE REVIEW

**Comment by deniak** [comment]
@tripu, rebase done!

File: lib/validator.js [hunk 1]
```diff
@@ -338,7 +338,7 @@ Specberus.prototype.getFeedbackDueDate = function() {
 
 Specberus.prototype.getDelivererIDs = function () {
     const REGEX_DELIVERER_URL = /^((https?:)?\/\/)?(www\.)?w3\.org\/2004\/01\/pp-impl\/\d+\/status(#.*)?$/i
-    ,   REGEX_DELIVERER_TEXT = /^public\s+list\s+of\s+any\s+patent\s+disclosures(\s+\(.+\))?$/i
+    ,   REGEX_DELIVERER_TEXT = /^(charter|public\s+list\s+of\s+any\s+patent\s+disclosures(\s+\(.+\))?)$/i
```
Comment (tripu) [inline lib/validator.js]: Why this change?

Comment (deniak) [inline lib/validator.js]: For IG notes, we don't have the regular patent policy boilerplate. So there's no "public list of any patent disclosures" link we can extract to get the deliverer ID.
However, the editors need to provide the charter disclosure link for that type of documents and from the [respec doc](https://github.com/w3c/respec/wiki/charterDisclosureURI), it does use the same link syntax. The resulting snapshot (e.g. [pwp](https://w3c.github.io/dpub-pwp/)) has the link on the word 'charter'.
